<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="lipika-Inspiron-3442" name="Default test" tests="4" failures="1" timestamp="27 Apr 2016 08:31:03 GMT" time="350.244" errors="0">
  <testcase name="verifyValidLogin" time="140.937" classname="com.wordpress.testcases.verifyWordpressLogin"/>
  <testcase name="verifyInValidUserIdLogin" time="1.936" classname="com.wordpress.testcases.verifyWordpressLogin">
    <failure type="java.lang.AssertionError" message="Failing the testcase deliberatly">
      <![CDATA[java.lang.AssertionError: Failing the testcase deliberatly
	at org.testng.Assert.fail(Assert.java:94)
	at com.wordpress.testcases.verifyWordpressLogin.verifyInValidUserIdLogin(verifyWordpressLogin.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- verifyInValidUserIdLogin -->
  <testcase name="verifyInValidPasswordLogin" time="1.807" classname="com.wordpress.testcases.verifyWordpressLogin">
    <skipped/>
  </testcase> <!-- verifyInValidPasswordLogin -->
  <testcase name="verifyLogout" time="156.518" classname="com.wordpress.testcases.verifyWordpressLogin"/>
</testsuite> <!-- Default test -->
